# Generated by Django 3.1.8 on 2023-10-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('E', 'Electric car'), ('N', 'Gas car')], max_length=2)),
            ],
        ),
    ]
