name: Python app
run-name: {{github.actor}} is testing out Github Actions!
on:
  push:
    branches: [ $default-branch ]
jobbs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      
      - name: set-up python 3.10
        uses: actions/setup-python@5.3.0
          with: 
            python-version: "3.10"
      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
